name: pisces_ordering
description: "An app for managing orders where clients can receive notifications when their order is ready for pickup."

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  audioplayers: ^5.2.1
  flutter_local_notifications: ^14.0.0
  intl: ^0.18.0
  unicode: ^1.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/audio/order_ready_notification.mp3
    - assets/icon/app_icon.png

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Path to your app icon
